server:
  port: 9090
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #cluster:
      #nodes: 100.98.100.242:7000,100.98.100.242:7001,100.98.100.242:7002,100.98.100.242:7003,100.98.100.242:7004,100.98.100.242:7005,100.98.100.242:7006,100.98.100.242:7007
    password:
    database: 0
  datasource:
    url:jdbc:mysql://localhost:3306/adam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false

spring.datasource.url=jdbc:mysql://localhost:3306/adam?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.jdbc.Driver